### ISSUE TITLE
背景图片如何关闭？

### ISSUE THREAD

**Issue by HanaeYuuma** [ZEROKISEKI/hexo-theme-gal#11]
因为背景图片是一直随机并且透明度和大小是变化的，看久了影响文章的阅读，所以想暂时关闭。
请问一下该如何关闭。

**Comment by HanaeYuuma** [comment]
我把_slideshow.scss中的opacity:0;修改为100
blog.js中的slideList[i]改为了'0'
可是当我查看文章的时候，过了一段时间还是会变化起来

**Comment by ZEROKISEKI** [comment]
如果不想要背景图片的话, 可以尝试把下面这段代码注释掉:
```

// ------- 处理背景图 --------------

var cdSlideShow = $('.cb-slideshow')
cdSlideShow.find('span').each(function (i, span) {
	$(this).css('backgroundImage', 'url(\'' + prefix + slideList[i] + ext + '\')')
})
// ------- 处理背景图结束 -----------

```

**Comment by HanaeYuuma** [comment]
@ZEROKISEKI 好的，感谢回复。

**Comment by HanaeYuuma** [comment]
根据上面的提示，已解决。
* 我把上面所说的内容注释了
* 并在_common.scss中把body{}内容中的的color注释了
* 并把background一行修改为background:  0% 0% / cover no-repeat fixed url(../imgs/slide/background0.jpg);
<br/>
谢谢
