### ISSUE TITLE
你好，请问首页’关于我‘页面找不到怎么自定义自己的？评论系统怎么添加？求指教，谢谢

### ISSUE THREAD

**Issue by reallinxu** [ZEROKISEKI/hexo-theme-gal#14]

**Comment by ZEROKISEKI** [comment]
评论系统在[wiki](https://github.com/ZEROKISEKI/hexo-theme-gal/wiki/%E8%AF%84%E8%AE%BA%E7%B3%BB%E7%BB%9F%E9%85%8D%E7%BD%AE%E8%AF%B4%E6%98%8E)有配置说明,  "关于我"页面, 是要自定义什么？如果是名称的话, 可以在`_config.yml`的**menu**那里有对应的属性可以改, 如果是页面布局,即要一个对应的模板的话, 可以参考`layout/page.ejs`的代码说明:

```
<!-- 搜索页面(尽可能接近ZanBlog搜索功能) -->
<% if(page.title === 'search') { %>
<%- partial('page/search', { item: page }) %>
<!-- 404页面 -->
<% } else if(page.title === '404') { %>
<%- partial('page/404') %>
<!-- 有其他想自定义的page在这里添加判断条件, 并且写好对应的模板渲染文件 -->
<% } else { %>
<%- partial('_partial/article', { item: page, isPage: true } ) %>
<% } %>
```
在上面的代码可以加多一个判断`page.title == 'about'`, 然后在`layout/page`文件夹下添加对应的`about.ejs`即可自定义这个页面的模板

如果不是上面说明的话, 具体描述一下是什么意思?

**Comment by reallinxu** [comment]
就是点击关于我，只要出来一段话之类的就可以了，ejs文件应该怎么写？不会nodejs，

**Comment by reallinxu** [comment]
谢谢，不太会前端的东西，我想关于我页面只打印一段话或者加几个图片，如果方便希望可以给一个模板，谢谢了

**Comment by ZEROKISEKI** [comment]
写几句话或者加几个图片不需要什么模板的, 你直接在markdown写就行了

**Comment by ZEROKISEKI** [comment]
在`source/about/index.md`下编辑

**Comment by reallinxu** [comment]
对于评论系统，我新建了一个repository，然后repo填此地址，但是评论提交没反应，怎么回事？

**Comment by reallinxu** [comment]
而且在评论系统上面还出现了一个error，not found，麻烦看一下：https://reallinxu.github.io/

**Comment by ZEROKISEKI** [comment]
贴一下`_config.yml`的comment部分代码

**Comment by ZEROKISEKI** [comment]
看了一下错误:
```
https://api.github.com/repos/reallinxu/github.com/reallinxu/blogIssue.git/issues/comments?sort=created&direction=desc
```

好像你把`comment`的repo的名字填成了`github.com/reallinxu/blogIssue.git`, 应该是填`blogIssue`就可以了

**Comment by reallinxu** [comment]
你好，gitment配置好后出现Error: Validation Failed，好像是issue label不能超过50字符，可是我不知道在哪里修改，麻烦告知，谢谢。

**Comment by ZEROKISEKI** [comment]
@reallinxu 在你存放评论的那个repo下面可以进行label edit

`https://github.com/ZEROKISEKI/你的gitment repo名称/labels`

<img width="1028" alt="2018-03-27 09 55 25" src="https://user-images.githubusercontent.com/9923459/37942298-ffe1914a-31a4-11e8-9f53-d543d8f4afb9.png">

**Comment by reallinxu** [comment]
不是这个修改，是我在初始化时候就报这个错误，还没有存入repo

**Comment by ZEROKISEKI** [comment]
你把`source/post`对应的那片文章的名字(*.md)改短点试下

**Comment by reallinxu** [comment]
改短试过了，但是标题中文的时候仍是乱码

**Comment by ZEROKISEKI** [comment]
中文标题的话应该是被encodeURI了吧, 按照默认的gitment的做法这个很容易就超过限制了。。， 主题是直接用的gitment作者本人提供的gitment脚本[https://imsun.github.io/gitment/dist/gitment.browser.js](https://imsun.github.io/gitment/dist/gitment.browser.js), 你可以将这个脚本下下来放在`source/js/comment/gitment.browser.js`上面, 按照这个[PR](https://github.com/imsun/gitment/pull/111/files)进行修改，接着`layout/layout.ejs`的那个外链gitment.browser.js的script去掉, 换成`<%- js('js/comment/gitment.browser.js') %>`,  如果还是不行的话，那就是中文标题的字数比较多了。。

<img width="903" alt="2018-03-27 10 28 02" src="https://user-images.githubusercontent.com/9923459/37943312-a5f4858e-31a9-11e8-9eef-6a4ed532499b.png">

**Comment by reallinxu** [comment]
谢谢，我把地址改短了，文章名也改了就可以了，现在发现一个问题，gitment手机浏览器登录后会报错，object ProgressEvent，电脑登陆360浏览器有的可以，有的报同样的错误
