### ISSUE TITLE
请问一下这个效果为什么我不能正常显示

### ISSUE THREAD

**Issue by qq752177433** [ZEROKISEKI/hexo-theme-gal#15]
问一下这个 效果怎么得的，为什么我这边显示不出来，鼠标经过我只会图片放大，是不是要excerpt参数，但是我设置了也没用
![image](https://user-images.githubusercontent.com/36815458/37838289-7de83842-2ef2-11e8-8ae3-27227a2d991e.png)

**Comment by qq752177433** [comment]
还有网站的favicon图标该放在哪里，怎么设置

**Comment by ZEROKISEKI** [comment]
如果是文字内容的话, markdown文章`<!--more-->`前面的部分会作为显示的内容, 你可以决定要显示的部分, 在其后面添加`<!--more-->`

网站的favicon在根目录的`source/favicon.ico`中

**Comment by qq752177433** [comment]
谢谢，我知道原因了，我more之前的不是纯文本，就自动显示到下面去了，是我没认真看说明，谢谢耐心回答，还有，主题真的很好看！
