### ISSUE TITLE
对于评论系统的疑惑?

### ISSUE THREAD

**Issue by pheromone** [ZEROKISEKI/hexo-theme-gal#16]
我按照你的说明,注册了Gitment账号,也按照你的说明文档填好了各项参数,但是对于一开始的https://imsun.net/posts/gitment-introduction/   里面说的2.引入 Gitment 3. 初始化评论评论看不懂.

**Comment by ZEROKISEKI** [comment]
其实这个你稍微看下[gitment](https://github.com/imsun/gitment/)的代码和[github Issues API](https://developer.github.com/v3/issues/)就明白的。。,  把那个gitment Class大概看一遍就懂了，初始化评论实际上就是在目标repo创建一个issue来存储对应文章的评论

**Comment by pheromone** [comment]
我新建仓库,填写完参数之后.
![b8c37eb6-7cd3-4992-9f13-691a90778233](https://user-images.githubusercontent.com/14305431/37874222-dd3c1946-305d-11e8-8e0b-2030a82d7fdd.png)

**Comment by ZEROKISEKI** [comment]
@pheromone 可能是你的config.yml的配置repo填写了整个的地址，填一下repo的名称

**Comment by pheromone** [comment]
朋友,我快弄了1周评论了,最终还是没弄成功.可以详细说说他的第2,3步怎么操作吗?
<img width="741" alt="2018-03-30 10 33 55" src="https://user-images.githubusercontent.com/14305431/38141436-bace9198-346a-11e8-8e20-703353cf85b7.png">

**Comment by ZEROKISEKI** [comment]
你new这篇文章的名字是不是比较长或者是有中文。。，应该是超过了github labels长度的限制，可以看下这个[issue](https://github.com/ZEROKISEKI/hexo-theme-gal/issues/14#issuecomment-376375628), 也可以看下gitment的这个[issue](https://github.com/imsun/gitment/issues/118)

**Comment by ZEROKISEKI** [comment]
![问题图片](https://user-images.githubusercontent.com/9923459/37942298-ffe1914a-31a4-11e8-9f53-d543d8f4afb9.png)

**Comment by ZEROKISEKI** [comment]
或者你可以在`layout/layout.ejs`下添加Id:
```
<script>
    if(window.commentConfig) {
      window.commentConfig.id = '<%= page.date %>',
      window.commentConfig.owner = '<%= theme.comment.gitment.owner %>'
      window.commentConfig.repo = '<%= theme.comment.gitment.repo %>'
      window.commentConfig.client_id = '<%= theme.comment.gitment.oauth.client_id %>'
      window.commentConfig.client_secret = '<%= theme.comment.gitment.oauth.client_secret %>'
      window.commentConfig.redirect_uri = '<%= theme.comment.gitment.oauth.redirect_uri %>'
    } else {
      window.commentConfig = {
        id: '<%= page.date %>',
        owner: '<%= theme.comment.gitment.owner %>',
        repo: '<%= theme.comment.gitment.repo %>',
        client_id: '<%= theme.comment.gitment.oauth.client_id %>',
        client_secret: '<%= theme.comment.gitment.oauth.client_secret %>',
        redirect_uri: '<%= theme.comment.gitment.oauth.redirect_uri %>'
      }
    }
</script>
```

然后在`source/js/comment/gitment.js`下面对初始化gitment进行修改:

```
var gitment = new Gitment({
        id: window.commentConfig.id,
	owner: window.commentConfig.owner,
	repo: window.commentConfig.repo,
	oauth: {
		client_id: window.commentConfig.client_id,
		client_secret: window.commentConfig.client_secret
	},
	perPage: 10,
	title: window.commentConfig.title,
	theme: galTheme
})
```

**Comment by ZEROKISEKI** [comment]
我更新了代码，你试着拉下来后重新部署上去，试试能不能初始化评论

**Comment by pheromone** [comment]
谢谢

**Comment by pheromone** [comment]
重新拉取代码.可以在短文章里面评论,但是长文章无法评论,出现Error:Validation Failed,无法解决么?还有怎么评论仓库出现在文章里面了,还有一年空白文章.
![a8d89c08-bf08-4ffb-afb5-4d85c68514bb](https://user-images.githubusercontent.com/14305431/38162780-37176da6-351a-11e8-8c6d-79e7824376a9.png)

**Comment by ZEROKISEKI** [comment]
@pheromone 你那条评论是在哪里评论的?  存储评论的repo是这个对吧?[https://github.com/pheromone/comments/issues](https://github.com/pheromone/comments/issues), 我看了下issue, label应该是时间戳才对
<img width="1126" alt="2018-03-31 19 38 03" src="https://user-images.githubusercontent.com/9923459/38162857-7e25c9b2-351b-11e8-94e8-e4b10edb2631.png">

空白文章这个，你看一下leancloud的Counter里面那篇空白文章对应的url是什么，可能是bug :(

**Comment by ZEROKISEKI** [comment]
@pheromone `source/about/index.md`的title是不是空的?

**Comment by ZEROKISEKI** [comment]
博客仓库还是[pheromone.github.io](https://github.com/pheromone/pheromone.github.io)这个吧? 我看了跟我主题的代码还是不一样, 没有带id[https://github.com/pheromone/pheromone.github.io/blob/master/js/comment/gitment.js#L302](https://github.com/pheromone/pheromone.github.io/blob/master/js/comment/gitment.js#L302), 试试`hexo clean`清除下缓存后再重新生成部署

**Comment by pheromone** [comment]
非常感谢.终于搞定了.希望博客继续优化.祝君生活愉快.
