### ISSUE TITLE
the page looks bad

### ISSUE THREAD

**Issue by duanego** [ZEROKISEKI/hexo-theme-gal#19]
![image](https://user-images.githubusercontent.com/33107702/38064247-995ad06c-332f-11e8-8780-0d048af823a6.png)

**Comment by duanego** [comment]
what's wrong?

**Comment by ZEROKISEKI** [comment]
what's your browser？And，could you provide some pics about the stdout of the browser development tool console？

--------------原始邮件--------------
发件人："duanego "<notifications@github.com>;
发送时间：2018年3月29日(星期四) 上午9:02
收件人："ZEROKISEKI/hexo-theme-gal" <hexo-theme-gal@noreply.github.com>;
抄送："Subscribed "<subscribed@noreply.github.com>;
主题：Re: [ZEROKISEKI/hexo-theme-gal] the page looks bad (#19)
-----------------------------------

what's wrong?

**Comment by duanego** [comment]
Google chrome!I use the frp to put the website on the Internet.Now it is great!
http://www.dauness.xyz

**Comment by duanego** [comment]
Very beautiful theme!Now you can close the issue.
