### ISSUE TITLE
可以一起开发 吗

### ISSUE THREAD

**Issue by AmandaYi** [ZEROKISEKI/hexo-theme-gal#20]
/我也喜欢忧郁的弟弟, 我感觉功能和忧郁的弟弟wordpress网站还有很大的不足, 
所以希望能够一起开发,  希望能够加入 该项目

**Comment by ZEROKISEKI** [comment]
可以，你可以fork一下项目，进行新功能添加或者一些bug之类的完善，然后发起PR :)
