### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by wms-github** [ZEROKISEKI/hexo-theme-gal#21]
您好，在文章首页也就是文章列表页的中，当鼠标滑过每一篇文章时，在文章的图片上面显示的字在哪里设置？怎么实现

**Comment by ZEROKISEKI** [comment]
默认会将markdown文章的`<!--more-->`前面的文字作为显示的内容

**Comment by wms-github** [comment]
可是我使用这个标签之后，最后的效果是把这个标签之前的内容显示在图片的下面，而不是鼠标滑过图片时在图片上悬浮显示，这是怎么回事呢？还有就是我想问一下现在只有这种实现方式吗？可不可以自己想显示什么就显示什么？谢谢作者的解答

**Comment by ZEROKISEKI** [comment]
你的markdown文章是怎么样的，按道理说内容是不会显示在图片下面的(也有可能是浏览器的问题...)，这个效果是以[http://mygalgame.com/](http://mygalgame.com/)为模板实现的，目前只有这种方式, 目前考虑改配置多一个`preview_text`来自定义显示的内容
```
title: AndroidManifest Ambiguity方案实现
date: 2018-02-02 20:04:08
tags: Android逆向
preview: http://p1r8dwfrm.bkt.clouddn.com/AndroidManifest-Ambiguity方案实现/preview.jpg
preview_text: .....
```

**Comment by wms-github** [comment]
OK，谢谢作者，已解决！
