### ISSUE TITLE
怎么在文章中插入图片

### ISSUE THREAD

**Issue by dytiz** [ZEROKISEKI/hexo-theme-gal#23]
你好，我使用![](image/xxx.png)这种方式在文章中插入图片，背景图片没了，整个界面显的很暗，字都看不清楚了，请问你怎么插入图片的？谢谢~
@ZEROKISEKI

**Comment by ZEROKISEKI** [comment]
你是用什么方式插入图片的?

**Comment by ZEROKISEKI** [comment]
。。如果你要上传问题截图到这里的话，可以用下面的那个selecting them

<img width="574" alt="2018-04-18 13 25 18" src="https://user-images.githubusercontent.com/9923459/38913184-0125bcd4-430c-11e8-8d09-61b7c017f42e.png">

**Comment by ZEROKISEKI** [comment]
本地图片的话应该是相对路径`./`或者`../`这样的，你上面那个

> ！[图片描述]（/image/xx.png）

用的是绝对路径，所以会出错

**Comment by dytiz** [comment]
谢谢
