### ISSUE TITLE
对于category和tags的下拉菜单的个数配置.

### ISSUE THREAD

**Issue by pheromone** [ZEROKISEKI/hexo-theme-gal#26]
我新建了一个分类,也配置了
---
layout: posts
title: Android和React Native的简单交互
categories: 移动端学习
tags:  移动端学习
---
但是只有其他三个显示,唯独这个不显示.我也修改了显示的个数.
https://pheromone.github.io/   请帮我看看是哪里出错了.谢谢

![33abc914-1be3-45ea-9bff-805fda036c50](https://user-images.githubusercontent.com/14305431/40099387-52fccdd8-5912-11e8-95c5-5c8ca319cae4.png)
![fc02ef57-b8e2-4e94-83d1-51cb635db542](https://user-images.githubusercontent.com/14305431/40099388-534b55f2-5912-11e8-9d74-f8335e45237b.png)

**Comment by ZEROKISEKI** [comment]
.., 这个应该是我slice没有修改导致的, 我修改一下

**Comment by pheromone** [comment]
@ZEROKISEKI 意思是,我现在重新更新下就可以了吗?
