### ISSUE TITLE
登录后进行评论，请求地址是主页上URL配置项？

### ISSUE THREAD

**Issue by Joypigg** [ZEROKISEKI/hexo-theme-gal#29]
环境搭建的是本地计算机，文章下面，登录后评论功能这里，总是请求失败

**Comment by ZEROKISEKI** [comment]
本地配置的话你新建的oauth app的callback url为**http://localhost:4000/**，你请求失败出现的错误提示是什么

**Comment by Joypigg** [comment]
现在好了，核实了下，是github上的application app-id和密匙没改过来
