### ISSUE TITLE
使用过程中发现的一些小问题

### ISSUE THREAD

**Issue by Grinner2436** [ZEROKISEKI/hexo-theme-gal#33]
1.背景轮播图片
---------- themes\gal\layout\layout.ejs
[66]       maxCount: '<%- theme.slide_background.mac_count %>'
这里的变量名是mac_count ，但是在配置文件里面，外链和本地图片的配置项名称却分别是mac_count 和max_count
2.文章预览图片
 ---------- themes\gal\layout\_partial\head.ejs
57行
          previewsPreLoad.push(new Image())
		  previewsPreLoad[previewsPreLoad.length - 1].src = '<%- url_for('imgs/preview') %>' + previews[i]	
这里没有做url类型判断，一致作为本地图片来处理的。

**Comment by ZEROKISEKI** [comment]
第一点已经修正，关于第二点，那个部分的代码目前是注释掉的， 那部分本来是想测试预加载的...(url_for('imgs/preview')事实上是指存放blog的站点的图片链接, 当然本地测试自然就是本地图片链接了)

**Comment by Grinner2436** [comment]
我把两个问题都改了，然后就没错了。但是我竟然没注意到第二个问题其实是被注释的代码。
可能是我在定位第一个问题的时候，定位错了，跑到了那个被注释的代码上。
真是不错的一个主题，作者大大辛苦啦。默认还附赠点福利链接……口怕

**Comment by labbomb** [comment]
遇到了一个问题，搜索功能搜索后无法搜到任何东西，会报Cannot GET /content.json
这个content.json是404的
代码卡在这块了$.getJSON('<%- url_for('content.json') %>', function (json) {
      $('#search-breadcrumb').append(`搜索'${s}'的结果`)
      var result = getArticles(s, 'posts', json).concat(getArticles(s, 'pages', json))
      if (result.length === 0 || result.length <= (p - 1) * pageSize) {
      	// TODO 显示404页面
      } else {
        displaySearchResult(result.slice((p - 1) * pageSize, p * pageSize))
        displayPagination(result)
      }
    })

**Comment by ZEROKISEKI** [comment]
> 遇到了一个问题，搜索功能搜索后无法搜到任何东西，会报Cannot GET /content.json
> 这个content.json是404的
> 代码卡在这块了$.getJSON('<%- url_for('content.json') %>', function (json) {
> $('#search-breadcrumb').append(`搜索'${s}'的结果`)
> var result = getArticles(s, 'posts', json).concat(getArticles(s, 'pages', json))
> if (result.length === 0 || result.length <= (p - 1) * pageSize) {
> // TODO 显示404页面
> } else {
> displaySearchResult(result.slice((p - 1) * pageSize, p * pageSize))
> displayPagination(result)
> }
> })

在你的hexo站点目录下安装 hexo-generator-json-content

```
npm install hexo-generator-json-content --save

or 

cnpm install hexo-generator-json-content --save
```

如果后面你hexo g的时候有问题, 注意看看是不是这个json-content的问题, 如果是的话就是你的node比较老

接着在hexo站点目录的`_config.yml`下进行配置:

```
jsonContent:
  dateFormat: MM-DD
  pages:
    title: true
    text: true
    path: true
    date: true
    excerpt: true
    preview: true
  posts:
    title: true
    text: true
    path: true
    date: true
    excerpt: true
    tags: [{
      name: tag.name,
      slug: tag.slug,
      permalink: tag.permalink
    }]
    preview: true
```

重新`hexo clean`, `hexo g`, 再部署即可。
