### ISSUE TITLE
hexo-sass以及hexo-scss无法运行的问题

### ISSUE THREAD

**Issue by dizent** [ZEROKISEKI/hexo-theme-gal#36]
在运行hexo的命令时，其他都执行成功，但是在最前面会多两个错误：
`$ hexo g
(node:9948) [DEP0061] DeprecationWarning: fs.SyncWriteStream is deprecated.
ERROR Plugin load failed: hexo-renderer-sass
Error: EISDIR: illegal operation on a directory, read
ERROR Plugin load failed: hexo-renderer-scss
Error: EISDIR: illegal operation on a directory, read
INFO  Start processing
INFO  Files loaded in 273 ms
`
请问这个该怎么解决，站点根目录下的_config.yml已经加了jsonContent节点

**Comment by dizent** [comment]
nodejs是前两天刚下载的官网的8.11版本

**Comment by ZEROKISEKI** [comment]
cnpm install node-sass@latest
