### ISSUE TITLE
很棒的主题~目前搜索功能和移动设备背景好像无法解决？

### ISSUE THREAD

**Issue by SaraKale** [ZEROKISEKI/hexo-theme-gal#37]
这几天试用了作者的主题，很棒的主题！自己修改了喜欢的样式，可以预览下看看：[博客地址](https://sarakale.github.io/blog/)

只了解一点前端知识，学的基础都忘光了……目前我好像遇到几个bug：搜索功能无法实现的样子，看作者你的博客好像能搜索出来，不知道是不是这边仓库没更新～还有小型设备时搜索功能框也挺需要的；还有移动设备背景图是用默认的背景了……也没显示>_<
我都数不清自己魔改了啥233回头再仔细看看，像是font-awesome需要加到head.ejs才会显示图标等到之类的。
非常感谢作者开发了好可爱的主题！辛苦了！看了一圈问题列表，好像也有人遇到搜索功能的瓶颈了，这个不急，慢慢来完善~

另外，昨晚好奇搜了一圈评论系统，好像这个[valine](https://valine.js.org/)很不错的样子，也可以插入到hexo，是基于Leancloud的无后端评论系统。
只是我自己尝试修改了下，好像显示不出来·····不知道是不是要弄到网络上才显示出来……
作者如果有兴趣，也可以加入看看~目前gitment虽然挺好的，但是它还是需要注册登录……

**Comment by SaraKale** [comment]
啊~移动端背景我搞定了，自己改成外链就好了~~我好蠢233竟然没想到这招，但是想调用本地图片始终不行，可能是我运气不好2333作者不要在意我这个问题！ヽ（≧□≦）ノ
现在就差搜索功能解决啦~~
我再自力更生解决一下~

**Comment by Likefr** [comment]
我想问一下你的博客单击分类之后的页面里有分类列表是怎么写的呢

**Comment by SaraKale** [comment]
> 我想问一下你的博客单击分类之后的页面里有分类列表是怎么写的呢

分类目录是hexo自动创建的，我没有特别修改过，不过若需要自定义样式也可以写CSS定制。
分类要是博客路径下没有文件夹，可以新建一个：`hexo new page categories`

**Comment by Likefr** [comment]
能加个qq嘛 想咨询你一些问题

**Comment by SaraKale** [comment]
> 能加个qq嘛 想咨询你一些问题

有什么问题？这里可以简单说一下，要是不方便也可以直接给我发邮件： sarakale2017@gmail.com
QQ我很少上，有常见问题可以google搜索下看看，总会解决的。

**Comment by ZEROKISEKI** [comment]
最近才有空来修这些bug，搜索的bug和使用说明见 #46
