### ISSUE TITLE
建议作者更换评论系统

### ISSUE THREAD

**Issue by haig233** [ZEROKISEKI/hexo-theme-gal#39]
我按照您给出的教程安装gitment之后发现总是报[object XMLHttpRequestProgressEvent][object ProgressEvent] 这样的错误
建议更换成gitalk

**Comment by ZEROKISEKI** [comment]
这个跟gitment差不多，关于gitment的已经在[Issue #44](https://github.com/ZEROKISEKI/hexo-theme-gal/issues/44)修复了，不过可以在_config.yml中添加gittalk这个选项。
