### ISSUE TITLE
文章代码太长会超出.

### ISSUE THREAD

**Issue by rookiesmile** [ZEROKISEKI/hexo-theme-gal#4]
写代码的格式会超出页面~特别是在手机端明显
![hx09gc_h 8sqt haf1 jm55](https://user-images.githubusercontent.com/20514272/35026161-43354e66-fb84-11e7-817e-ff4e16f86577.png)
![ivyvn 2 dn 0kxfem30w k](https://user-images.githubusercontent.com/20514272/35026251-d6c3b55a-fb84-11e7-910b-b8383aae95ba.png)

**Comment by ZEROKISEKI** [comment]
修复了

**Comment by rookiesmile** [comment]
看见了~已添加~谢谢~效果不错~
