### ISSUE TITLE
现在的评论系统坏了?登录不了了

### ISSUE THREAD

**Issue by pheromone** [ZEROKISEKI/hexo-theme-gal#44]
现在的评论系统坏了?登录不了了.能修改下么?

**Comment by feijian123456** [comment]
这个好像是gitment作者自己的站点证书过期的关系，[https://github.com/imsun/gitment/issues/170](https://github.com/imsun/gitment/issues/170)

**Comment by pheromone** [comment]
@feijian123456  那太惨了.原作者好像也弃坑了.

**Comment by ZEROKISEKI** [comment]
看看能不能换成valine吧

**Comment by zoniony** [comment]
希望作者能有空fix下: )

**Comment by ZEROKISEKI** [comment]
目前将对gitment.browser.js的引用（https://imsun.github.io/gitment/dist/gitment.browser.js）换成了https://myau.moe/js/comment/gitment.browser.js，gitment评论可以使用了，valine的话近期看看。

**Comment by zoniony** [comment]
> 目前将对gitment.browser.js的引用https://imsun.github.io/gitment/dist/gitment.browser.js换成了https://myau.moe/js/comment/gitment.browser.js，gitment评论可以使用了，valine的话近期看看。

thx

**Comment by pheromone** [comment]
感谢大佬.
