### ISSUE TITLE
隐约记得你之前做出一个小玩偶的效果.请问现在是被去除了吗?

### ISSUE THREAD

**Issue by pheromone** [ZEROKISEKI/hexo-theme-gal#45]
隐约记得你之前做出一个小玩偶的效果.请问现在是被去除了吗?
就如下面这个?
https://huaji8.top/post/azusa/
![image](https://user-images.githubusercontent.com/14305431/50380742-210aac80-06ac-11e9-9e42-06ce050f5e8a.png)

**Comment by ZEROKISEKI** [comment]
你说的应该是[hexo-helper-live2d](https://github.com/EYHN/hexo-helper-live2d/blob/master/README.zh-CN.md)吧，这个可以hexo用户自己添加，不包含在hexo主题里面的。

**Comment by pheromone** [comment]
谢谢大佬,很可爱的2d效果.
