### ISSUE TITLE
为什么点击导航栏里面的标签和种类都是404？

### ISSUE THREAD

**Issue by Lee981265** [ZEROKISEKI/hexo-theme-gal#48]
![image](https://user-images.githubusercontent.com/29849554/51727275-38232c80-20a6-11e9-8656-f899c30567df.png)

**Comment by Lee981265** [comment]
![image](https://user-images.githubusercontent.com/29849554/51727296-4d985680-20a6-11e9-8341-92763ad943f8.png)

**Comment by ZEROKISEKI** [comment]
查询一下hexo 如何添加categories和tags

**Comment by Lee981265** [comment]
如果是分类下一级目录是不报错的

**Comment by Lee981265** [comment]
![image](https://user-images.githubusercontent.com/29849554/51729513-05316680-20af-11e9-971f-c5e1e8ead68b.png)

**Comment by ZEROKISEKI** [comment]
<img width="776" alt="2019-01-25 14 49 04" src="https://user-images.githubusercontent.com/9923459/51729897-7887a800-20b0-11e9-9ea7-43bc2e42d685.png">

**Comment by Lee981265** [comment]
谢谢大佬
