### ISSUE TITLE
请问文章热度的数据是存储在哪里的

### ISSUE THREAD

**Issue by xnervwang** [ZEROKISEKI/hexo-theme-gal#5]
如题，求问。还是说热度不是根据点击量来的，而是需要作者设定一个值，或者是随机生成的？

**Comment by ZEROKISEKI** [comment]
热度统计说明参照[wiki](https://github.com/ZEROKISEKI/hexo-theme-gal/wiki/%E6%96%87%E7%AB%A0%E7%83%AD%E5%BA%A6%E7%BB%9F%E8%AE%A1%E9%85%8D%E7%BD%AE%E8%AF%B4%E6%98%8E)， 具有热度统计的文章在leancloud.cn的后台可以看到,目前该主题的设置是点击量，当然你也可以在leancloud.cn的后台进行手动编辑热度，如下图所示:

![截图](http://oyfn84vnv.bkt.clouddn.com/2018-1-24-2.png)

**Comment by xnervwang** [comment]
好的，非常感谢！
