### ISSUE TITLE
朋友,我的博客侧边评论栏出现 部分点击跳转路由出错.

### ISSUE THREAD

**Issue by pheromone** [ZEROKISEKI/hexo-theme-gal#55]
https://pheromone.github.io/
<img width="428" alt="WeChat472d08adf4ceac9c033df176de744629" src="https://user-images.githubusercontent.com/14305431/55373085-9fda7580-5536-11e9-9efb-668418ccda0a.png">
![1733CADE-845B-4C7E-9603-F82FA03920E1](https://user-images.githubusercontent.com/14305431/55373091-a537c000-5536-11e9-904b-81039ee6a934.png)

**Comment by feijian123456** [comment]
你是不是换过目录？

**Comment by feijian123456** [comment]
可能你用以前React&&Native目录的时候初始化了github issue, 后面换了目录但是issue没改。

**Comment by feijian123456** [comment]
![1](https://user-images.githubusercontent.com/9881674/55406435-b4e2f300-558e-11e9-92b3-acc63a9e3df5.png)
![2](https://user-images.githubusercontent.com/9881674/55406436-b4e2f300-558e-11e9-8390-9c01de2d8f05.png)

**Comment by pheromone** [comment]
恩.那请问怎么修改.

**Comment by feijian123456** [comment]
@pheromone 你尝试把对应issue的内容换成正确的地址。

**Comment by feijian123456** [comment]
![1](https://user-images.githubusercontent.com/9881674/55406528-e0fe7400-558e-11e9-9f94-7c7b95a1e781.png)

**Comment by feijian123456** [comment]
@pheromone  就是你那个地址换成你那篇文章的地址试试

**Comment by pheromone** [comment]
@feijian123456 恩.可以.谢谢
