### ISSUE TITLE
突然间发现,博客打开有时候需要翻墙.

### ISSUE THREAD

**Issue by pheromone** [ZEROKISEKI/hexo-theme-gal#58]
http://pheromone.github.io/message/
比我这个留言板第三页. 有时不需要有时又需要的.....

**Comment by psc2350** [comment]
请问这问你有解决吗?
我在中国的朋友想访问我的网站的某些页面也会出现404(github的404)
有些页面则不会
而且不是所有在中国的朋友都这样

**Comment by pheromone** [comment]
@psc2350  我的也是在部分地区会出现这个情况.没办法.ZF的搞得恶心事..
