### ISSUE TITLE
无法登陆了.

### ISSUE THREAD

**Issue by pheromone** [ZEROKISEKI/hexo-theme-gal#59]
![image](https://user-images.githubusercontent.com/14305431/56483405-645f1580-64fc-11e9-941a-eb4e7fdbbd9d.png)

证书过期了么.

**Comment by feijian123456** [comment]
[https://myau.moe](https://myau.moe) 可以登录和评论啊，证书没过期啊

**Comment by feijian123456** [comment]
你站点的style.css好像不见了

**Comment by pheromone** [comment]
@ feijian123456  对.你有么.我的刚被我搞丢了

**Comment by feijian123456** [comment]
hexo d清除猴重新hexo g不就有了吗

**Comment by pheromone** [comment]
@feijian123456  我试了,不行呀

**Comment by ZEROKISEKI** [comment]
重新npm install一下
，可能是node-sass那些插件的问题

**Comment by ZEROKISEKI** [comment]
[https://github.com/hexojs/hexo/issues/1373](https://github.com/hexojs/hexo/issues/1373)

**Comment by pheromone** [comment]
@ZEROKISEKI  恩,我重新安装了下 sass插件就好了. 
评论无法初始化.无法登陆呢? 是不是也是这个问题.
![image](https://user-images.githubusercontent.com/14305431/56487910-5bc40a80-650f-11e9-8790-685aeebc2054.png)

**Comment by ZEROKISEKI** [comment]
你登录之后会出现一个初始化issue的按钮，点击按钮初始化就行了

**Comment by pheromone** [comment]
我点击登陆就自动返回首页了.

**Comment by ZEROKISEKI** [comment]
大概是你那几篇文章的标题带了空格，redirect_uri出错了

**Comment by ZEROKISEKI** [comment]
https://pheromone.github.io/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https://developer.github.com/apps/managing-oauth-apps/troubleshooting-authorization-request-errors/#redirect-uri-mismatch

**Comment by pheromone** [comment]
感谢.
