### ISSUE TITLE
标签云页面不显示

### ISSUE THREAD

**Issue by xnervwang** [ZEROKISEKI/hexo-theme-gal#6]
作者您好。我初始化博客后，标签云页面的标签列表是空的，但是显然我是有很多Tags的。请问这个页面需要特殊配置才能正确生成吗？

![image](https://user-images.githubusercontent.com/4509104/35479524-9f30613e-0434-11e8-8665-cb70257b6a93.png)

**Comment by ZEROKISEKI** [comment]
这个标签云的页面的url是什么?不像是/tags的页面

**Comment by xnervwang** [comment]
本地url是http://127.0.0.1:4000/tags/

source\tags\index.md的内容是：
title: 标签云
date: 2015-10-01 12:39:04
type: "tags"
---

在next theme下是能正常生成tags页面的。

**Comment by ZEROKISEKI** [comment]
你试着这样加:
```

---
title: 标签云
date: 2015-10-01 12:39:04
type: "tags"
layout: "tags"
comments: false
---

```

**Comment by xnervwang** [comment]
OK，现在能正常显示了，非常感谢！建议把这个配置加在wiki中，google了一下发现好像有一些theme都需要layout: "tags"这个配置项。

![image](https://user-images.githubusercontent.com/4509104/35479661-ae773ae8-0437-11e8-9a4c-b4fc80c6726d.png)

另外再提一个小小的建议，categories和tags页面都是这个不透明的淡蓝色文字背景，但是我注意到忧郁的弟弟原站用的是半透明的淡蓝色文字背景，半透明的效果看起来会更好些。

![image](https://user-images.githubusercontent.com/4509104/35479679-1beb1c84-0438-11e8-967f-9fd3b24b1dff.png)

**Comment by ZEROKISEKI** [comment]
Added.
