### ISSUE TITLE
有个问题咨询下

### ISSUE THREAD

**Issue by pheromone** [ZEROKISEKI/hexo-theme-gal#63]
我使用了你的博客和评论系统,然后我购买了个域名关联之后,发现无法登录评论了?
http://zhoushaoting.com/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch

**Comment by feijian123456** [comment]
可能是与你之前配置的ouah-app的域名不一致？

**Comment by pheromone** [comment]
@feijian123456 
之前的ouah-app在哪里设置?
![image](https://user-images.githubusercontent.com/14305431/64074635-805f9880-cce0-11e9-954d-02c24d4d1ff0.png)
![image](https://user-images.githubusercontent.com/14305431/64074636-93726880-cce0-11e9-92a3-2bd8d33ad222.png)

**Comment by pheromone** [comment]
谢谢楼上. 
![image](https://user-images.githubusercontent.com/14305431/64074749-f3b5da00-cce1-11e9-8a08-9be120ce0488.png)
