### ISSUE TITLE
大佬,麻烦看下,无法登录了?

### ISSUE THREAD

**Issue by shaoting0730** [ZEROKISEKI/hexo-theme-gal#70]
https://zhoushaoting.com/

**Comment by ZEROKISEKI** [comment]
[https://github.com/ZEROKISEKI/hexo-theme-gal/issues/59](https://github.com/ZEROKISEKI/hexo-theme-gal/issues/59)

**Comment by shaoting0730** [comment]
@ZEROKISEKI  我这个问题好像不是这个原因啊.我测试下不行

**Comment by ZEROKISEKI** [comment]
看了下，可能是你存放的comment的那些Issue的labels有问题(带的是一个gitment外加一个时间。。。)，试一下把时间的那个label修改为对应链接的url试试?

**Comment by ZEROKISEKI** [comment]
可能是你存放的comment的那些Issue的labels有问题(带的是一个gitment外加一个时间。。。)，把时间的那个label修改为对应链接的url试试?

**Comment by shaoting0730** [comment]
是这个?
![image](https://user-images.githubusercontent.com/14305431/73266704-66d06780-4212-11ea-9878-372e387c8e24.png)
![image](https://user-images.githubusercontent.com/14305431/73266986-00981480-4213-11ea-8373-126d45c66386.png)

**Comment by ZEROKISEKI** [comment]
不知道你的label为什么会是日期的格式，gitment默认创建的label应该是window.location.href的

**Comment by shaoting0730** [comment]
@ZEROKISEKI   ???没理解你说的.那有啥办法抢救下么·?

**Comment by shaoting0730** [comment]
@ZEROKISEKI 之前是好的,但是上传了这篇博客就不行了..... 
 https://zhoushaoting.com/2020/01/23/%E7%A7%BB%E5%8A%A8%E7%AB%AF%E5%AD%A6%E4%B9%A0/Flutter~%E8%87%AA%E5%AE%9A%E4%B9%89tabbar%E6%A8%A1%E5%9D%97/
