### ISSUE TITLE
点击登录，出现一个弹窗。[object ProgressEvent]

### ISSUE THREAD

**Issue by shaoting0730** [ZEROKISEKI/hexo-theme-gal#75]
点击登录，出现一个弹窗。[object ProgressEvent]

https://zhoushaoting.com/2019/09/07/%E7%A7%BB%E5%8A%A8%E7%AB%AF%E5%AD%A6%E4%B9%A0/Flutter~Flare%E5%8A%A8%E7%94%BB%E5%AD%A6%E4%B9%A0/

![image](https://user-images.githubusercontent.com/14305431/79045446-bc2aeb00-7c3d-11ea-969f-47c224e657c6.png)

**Comment by feijian123456** [comment]
oauth的证书过期了，现在应该可以了

**Comment by shaoting0730** [comment]
@feijian123456  谢谢
