### ISSUE TITLE
 1

### ISSUE THREAD

**Issue by ghost** [ZEROKISEKI/hexo-theme-gal#80]

**Comment by shangzhenglin** [comment]
评论那个配置的链接失效了，哪位大哥教一下如何配置gitment，仓库和OAuth Apps都么有填错，但是我的那个一直报错

**Comment by fnsflm** [comment]
`gal/layout/_partial/footer.ejs`可以改
这并不需要其它人告诉你, 在项目里搜索2018就能找到

**Comment by fnsflm** [comment]
应该是原本的证书过期了,  #79 我找到的一个好像也不能用了.
https://github.com/imsun/gitment/issues/170 实在不行自己搭一个吧

**Comment by ghost** [comment]
> `gal/layout/_partial/footer.ejs`可以改
> 这并不需要其他人告诉你，在项目里搜索2018就能找到

啊，谢谢，不好意思，我刚开始学。十分感谢
