### ISSUE TITLE
背景图不轮播了(网络原因?)

### ISSUE THREAD

**Issue by RicoAfoat** [ZEROKISEKI/hexo-theme-gal#86]
### RT
在更换背景之后,它不轮播了.
只会加载一张背景图(每次刷新之后不一样,我想这排除了我的命名问题),导致后面完全是黑的.
~~preview功能没有出现任何问题~~
我尝试寻找图床,但是并没有找到支持命名(指背景图名称得是123456的顺序)的外链
我尝试发挥自己动手进行魔改主题,但仅仅完成了更改"天若有情天亦老"的部分(笑)
~~我发誓我只更改了这一部分并且.yml文件配置十分正常~~
Edge在开发者模式下"源"中也只看到了一张图片(是哪一张完全随机)
可能是遭了天诺战士的怨气罢(doge)
~~由于目前的自己暂时不会前端css,js等技术,所以在[此](https://dbsznice.github.io)伸手求巨佬解决问题~~
~~后辈的第一次submit new issue,值得纪念~~

又及:
求推荐的图床和服务器

**Comment by fnsflm** [comment]
背景图不能轮播是本地还是远程? 更换背景之后不轮播意思是换之前功能是正常的? 可以考虑更换图片或对图片进行处理, 比如压缩剪裁缩放. 也可以试着换个浏览器或者换个设备试试. 如果怀疑自行魔改出了问题可以考虑重新clone然后部署一次.如果还不能解决, 可以直接去看源码, js相关代码在`gal/layout/layout.ejs`第63行起, `gal/source/js/blog.js`第32行起, css在`gal/source/css/_slideshow.scss`

图床的话, 像七牛云这种直接给你免费对象存储作为图床, 命名不成问题. 我用的是github公共仓库为图床, 再配上jsdelivr加速.

**Comment by RicoAfoat** [comment]
好了,我似乎找到了为什么,稍微有一点点搞笑
我确实只魔改了`gal/layout/_partial/slideshow.ejs`
在经过实验之后我发现:slideshow.ejs中输出的行数=加载的背景图数 : )
~~在本地和远程,多个设备上都适用~~
