### ISSUE TITLE
原来的评论系统去除了？

### ISSUE THREAD

**Issue by shaoting0730** [ZEROKISEKI/hexo-theme-gal#87]
原来的评论系统去除了？

**Comment by fnsflm** [comment]
没, 这个项目以经至少两年没更新了, 所用的gitment评论区也停止维护了

**Comment by shaoting0730** [comment]
好吧。谢谢~不过昨天我按照你写的配置配置了下，发现没有用呢？是不是必须得使用你的新模板才有效果。 @fnsflm
