### ISSUE TITLE
界面显示不正常

### ISSUE THREAD

**Issue by pipigou** [ZEROKISEKI/hexo-theme-gal#9]
系统正常启动后，界面显示不正常
![error](https://user-images.githubusercontent.com/8373214/36341513-50ed3c58-142a-11e8-8ba9-f81d58323914.jpg)
具体原因是什么？谢谢！！！

**Comment by ZEROKISEKI** [comment]
看样子好像是没有加载部分样式文件，f12看下开发者工具的console有没有对应的错误提示？

**Comment by ZEROKISEKI** [comment]
对应渲染scss文件的npm包`hexo-renderer-sass`和`hexo-renderer-scss`是否有全部安装？

**Comment by pipigou** [comment]
不好意思没有仔细看文档
